# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ff2c5f7c9bbb183b46024841d01f6e2bb68acf1d6d14036a009b579f16c44b52aaf6b90a39fb7ad14e0305d4473af6a48d4b05cabcdcbc0e9a93a6fd4b62c3c

test:
  secret_key_base: 4b79abd5ec124ae2ebfa07303ce1fa5122553111de71e238d918e07c8bc6538e2ecccde6980d17479eb20a0d72da8fae9e7f6be13af0af6e147a9245c051f605

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
